# Generated by Django 5.2.5 on 2025-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('plan_per_week', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
