# Generated by Django 5.2.5 on 2025-09-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('wb_rate', models.DecimalField(decimal_places=4, default=0.25, max_digits=6)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.04, max_digits=6)),
                ('acos', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('logistics', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('storage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='plans.categoryprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkuMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_month', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='plans.sku')),
            ],
        ),
        migrations.CreateModel(
            name='SkuOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acos', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('logistics', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('storage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('returns', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plans.categoryprofile')),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='plans.sku')),
            ],
        ),
    ]
