# Generated by Django 5.2.5 on 2025-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_categoryprofile_sku_skumetrics_skuoverride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skuoverride',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skumetrics',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='skuoverride',
            name='sku',
        ),
        migrations.AddField(
            model_name='plan',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CategoryProfile',
        ),
        migrations.DeleteModel(
            name='SkuMetrics',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.DeleteModel(
            name='SkuOverride',
        ),
    ]
